services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    privileged: true
    tty: true
    volumes:
      - ./app:/app